---
- name: DMVPN IPSEC TEMPLATE
  hosts: routers
  gather_facts: True

  tasks:

    - name: Configure ISAKMP and IPSEC Attributes
      ios_config:
        lines:
          - crypto ikev2 proposal DMVPN
          - encryption aes-cbc-256
          - integrity sha256
          - group 20
          - crypto ikev2 policy DMVPN_POLICY
          - proposal DMVPN
          - crypto ikev2 keyring DMVPN_KEYRING
          - peer dmvpn-node
          - address 0.0.0.0 0.0.0.0
          - pre-shared-key cisco123
          - crypto ikev2 profile DMVPN_PROFILE
          - match address local 200.1.1.1
          - match identity remote address 200.1.2.2 255.255.255.255
          - match identity remote address 200.1.3.3 255.255.255.255
          - authentication remote pre-share
          - authentication local pre-share
          - keyring local DMVPN_KEYRING
          - crypto ipsec transform-set DMVPN_TRANSFORM esp-3des esp-sha256-hmac
          - mode tunnel
          - crypto ipsec profile IKEv2_PROFILE
          - set transform-set DMVPN_TRANSFORM
          - set ikev2-profile DMVPN_PROFILE
