---
- name: SW1 DMVPN UNDERLAY CONFIF
  hosts: SW1
  gather_facts: True

  tasks:

    - name: Change switchports to L3 ports and Turn on Routing
      ios_config:
        lines:
          - ip routing
          - int range G1/0 - 2
          - no switchport

    - name: Configure SW Interfaces for DMVPN connections
      ios_l3_interfaces:
        config:
          - name: GigabitEthernet1/0
            ipv4:
            - address: 200.1.1.10/24
          - name: GigabitEthernet1/1
            ipv4:
            - address: 200.1.2.10/24
          - name: GigabitEthernet1/2
            ipv4:
            - address: 200.1.3.10/24
        state: merged

      register: output

    - name: show output
      debug:
        var: output.stdout_lines

    - name: Configure Interface Attributes
      ios_interfaces:
        config:
          - name: GigabitEthernet1/0
            description: INT-TO-R1
            enabled: True
          - name: GigabitEthernet1/1
            description: INT-TO-R2
            enabled: True
          - name: GigabitEthernet1/2
            description: INT-TO-R3
            enabled: True

      register: output

    - name: show output
      debug:
        var: output.stdout
